name: future_builder_ex
version: 1.0.0
description: An improved version of FutureBuilder
repository: https://github.com/bsutton/flutter_builder_ex
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  logger: ^1.1.0
  stacktrace_impl: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
